version: "3.8"

services:
  redis:
    image: redis:7.0.2-alpine
    container_name: test-redis
    ports:
      - "6378:6378"
    expose:
      - "6378"

  backend:
    build: Dockerfile
    container_name: test-backend
    volumes:
      - .:/src/app/
    ports:
      - "8008:8008"
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - redis
